// packages/svelte/src/lib/consent/ConsentGate.svelte
<script lang="ts">
  import type { ConsentExpr } from "@openpolicy/core/consent";
  import type { Snippet } from "svelte";
  import { getConsent } from "./context.svelte";

  type Props = {
    requires: ConsentExpr;
    children?: Snippet;
    fallback?: Snippet;
  };

  let { requires, children, fallback }: Props = $props();

  const consent = getConsent();
  const active = $derived(consent.has(requires) ? children : fallback);
</script>

{#if active}
  {@render active()}
{/if}

// packages/react/src/components/ConsentGate.tsx
import type { ReactNode } from "react";
import type { HasExpression } from "../context";
import { useCookieConsent } from "../context";

interface ConsentGateProps {
	requires: HasExpression;
	fallback?: ReactNode;
	children: ReactNode;
}

export function ConsentGate({
	requires,
	fallback = null,
	children,
}: ConsentGateProps) {
	const { has } = useCookieConsent();
	return has(requires) ? children : fallback;
}
